### ISSUE TITLE
Add Microsoft Bond

### ISSUE THREAD

**Issue by dotnetchris** [leo-gan/GLD.SerializerBenchmark#2]
Microsoft Bond is a new (but actually v3) product from Microsoft for high performance serialization with condensed messages. It is meant as an alternative to Protobuf https://github.com/Microsoft/bond

**Comment by leo-gan** [comment]
Yeah, that's right. It was announced only in January 2015.

**Comment by dotnetchris** [comment]
Yes they kept it internal for years, it's been plumbing Azure for a long time

**Comment by leo-gan** [comment]
I've added some comments about Bond in ReadMe.

**Comment by leo-gan** [comment]
It was added. And it works badly :(

**Comment by dotnetchris** [comment]
Do you have any links to what you added? I can't seem to find anything relevant in https://github.com/leo-gan/GLD.SerializerBenchmark/commits/master

**Comment by leo-gan** [comment]
For example this one (there are others in this folder)
https://github.com/leo-gan/GLD.SerializerBenchmark/blob/master/GLD.SerializerBenchmark/Serializers/BondCompactSerializer.cs

Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/

**Comment by dotnetchris** [comment]
When you said it works poorly, did you account for warm up time? 

https://microsoft.github.io/bond/manual/bond_cs.html 
// The first calls to Serialize.To and Deserialize<T>.From can take
// a relatively long time because they generate the de/serializer 
// for a given type and protocol.

**Comment by leo-gan** [comment]
Sure.
Poorly means, it didn't pass many tests with complex data types. Maybe I
missed something in attributes for such data...

Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/
