### ISSUE TITLE
NFX.Serialization.Slim

### ISSUE THREAD

**Issue by itadapter** [leo-gan/GLD.SerializerBenchmark#4]
Not an issues, rather a request, would be interesting to see the NFX.Slim in the mix, since you already have an extensive framework for comparison tests.

https://github.com/aumcode/nfx/blob/master/Source/NFX/Serialization/Slim/SlimSerializer.cs

use cases, notably support for cyclical graphs, readonly fields in structs etc..:

https://github.com/aumcode/nfx/blob/master/Source/Testing/NUnit/NFX.NUnit/Serialization/Slim.cs#L1567

The NFX is not available as NuGet as it is a UNISTACK (no packages by definition) solution.
Just build an NFX.dll and drop in.

**Comment by leo-gan** [comment]
Thanks for help!
I've added it. Please, feel free to improve code. I've done only basic things, because the whole purpose of the benchmark is to provide simple samples.

**Comment by itadapter** [comment]
Leo, the slim serializer tests needs to have TypeRegistry added, as otherwise it will emit all used type names into the output.  All types that are used in the graph need to be added like so:
https://github.com/aumcode/nfx/blob/master/Source/Testing/NUnit/NFX.NUnit/Serialization/Slim.cs#L1010-1015

Intead of common types, add the types like Person, CrimeRecord and others from your sample.
This will shrink output by 95%
